<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="Npgsql" Version="9.0.5" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PruebaAbank.Aplicacion\PruebaAbank.Aplicacion.csproj" />
    <ProjectReference Include="..\PruebaAbank.Dominio\PruebaAbank.Dominio.csproj" />
  </ItemGroup>

</Project>
